# Build, push TechTrends app as docker img to DockerHub
name: TechTrends - Package with Docker

# Trigger on every push to the main branch
on:
  push:
    branches:
      - 'main'

# Run the CI pipeline
jobs:
  build-and-push-techtrends:
    # Run on latest Ubuntu OS.
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: project/
          file: project/Dockerfile
          push: true
          tags: saisuhas/techtrends:latest

